# Generated by Django 4.1 on 2025-12-08 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
