# Generated by Django 6.0.2 on 2026-02-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panservice', '0003_state_remove_userprofile_raw_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
