# Generated by Django 6.0.2 on 2026-02-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panservice', '0007_remove_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='usertype',
            field=models.CharField(choices=[('state', 'State Distributor'), ('district', 'District Distributor'), ('retailer', 'Retailer')], max_length=20),
        ),
    ]
