# Generated by Django 6.0.2 on 2026-02-24 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panservice', '0008_alter_userprofile_usertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_approve',
            new_name='is_approved',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='usertype',
        ),
        migrations.AlterField(
            model_name='user',
            name='pan_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
