# Generated by Django 6.0.2 on 2026-02-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panservice', '0009_rename_is_approve_userprofile_is_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleRegistrationCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('state', 'State Distributor'), ('district', 'District Distributor'), ('retailer', 'Retailer')], max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='pan_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('state', 'State Distributor'), ('district', 'District Distributor'), ('retailer', 'Retailer')], default='retailer', max_length=20),
        ),
    ]
