# Generated by Django 6.0.2 on 2026-02-25 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panservice', '0010_roleregistrationcharge_alter_user_pan_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='district',
        ),
    ]
