# Generated by Django 6.0.2 on 2026-02-26 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panservice', '0011_remove_userprofile_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='aadhar',
            new_name='aadhaar',
        ),
    ]
