# Generated by Django 6.0.2 on 2026-02-26 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panservice', '0012_rename_aadhar_userprofile_aadhaar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pan_rate',
        ),
    ]
