# Generated by Django 6.0.2 on 2026-02-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panservice', '0013_remove_user_pan_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
    ]
