# Generated by Django 6.0.2 on 2026-02-27 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panservice', '0014_user_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
