# Generated by Django 6.0.2 on 2026-03-02 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panservice', '0015_alter_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='wallet_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panservice.walletrequest'),
        ),
    ]
