# Generated by Django 6.0.2 on 2026-03-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panservice', '0017_userprofile_uti_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleCouponPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('state', 'State Distributor'), ('district', 'District Distributor'), ('retailer', 'Retailer')], max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
