# Generated by Django 6.0.2 on 2026-03-03 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panservice', '0018_rolecouponprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='uti_price',
        ),
    ]
