# Generated by Django 6.0.2 on 2026-03-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panservice', '0019_remove_userprofile_uti_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='coupons_available',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
