# Generated by Django 6.0.2 on 2026-03-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panservice', '0020_userprofile_coupons_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolecouponprice',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('state', 'State Distributor'), ('district', 'District Distributor'), ('retailer', 'Retailer')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='roleregistrationcharge',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('state', 'State Distributor'), ('district', 'District Distributor'), ('retailer', 'Retailer')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('state', 'State Distributor'), ('district', 'District Distributor'), ('retailer', 'Retailer')], default='retailer', max_length=20),
        ),
    ]
