# Generated by Django 6.0.2 on 2026-03-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panservice', '0021_alter_rolecouponprice_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
