# Generated by Django 6.0.2 on 2026-03-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panservice', '0022_userprofile_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='registration_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
