# Generated by Django 6.0.2 on 2026-03-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panservice', '0024_userprofile_company_userprofile_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='registration_charge',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='margin_slab',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nsdl_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='uti_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
