# Generated by Django 6.0.2 on 2026-03-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panservice', '0025_remove_userprofile_registration_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='margin_slab',
            field=models.CharField(blank=True, choices=[('default', 'Default'), ('ssc_retailer', 'SSC Retailer')], max_length=50, null=True),
        ),
    ]
