# Generated by Django 6.0.2 on 2026-03-06 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panservice', '0026_alter_userprofile_margin_slab'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='account_number',
            new_name='upi_id',
        ),
    ]
