# Generated by Django 6.0.2 on 2026-03-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panservice', '0027_rename_account_number_userprofile_upi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissiontransaction',
            name='txn_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], default='credit', max_length=10),
        ),
    ]
