# Generated by Django 6.0.2 on 2026-03-07 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panservice', '0028_commissiontransaction_txn_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissiontransaction',
            name='coupon_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panservice.couponpurchase'),
        ),
        migrations.AlterField(
            model_name='commissiontransaction',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_generated', to=settings.AUTH_USER_MODEL),
        ),
    ]
