# Generated by Django 5.1.3 on 2026-04-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panservice", "0029_alter_commissiontransaction_coupon_request_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="couponpurchase",
            name="request_again",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="closing_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="opening_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="couponpurchase",
            name="approved_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="couponpurchase",
            name="done",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
