# Generated by Django 5.1.4 on 2026-05-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panservice', '0030_couponpurchase_request_again_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSAMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psa_login_id', models.CharField(max_length=150, unique=True)),
                ('psa_password', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
