# Generated by Django 5.1.4 on 2026-05-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panservice', '0031_psamaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='psamaster',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='psamaster',
            name='status',
            field=models.CharField(choices=[('issued', 'Issued'), ('started', 'Started'), ('partially_completed', 'Partially Completed'), ('fully_completed', 'Fully Completed')], default='issued', max_length=20),
        ),
    ]
