# Generated by Django 5.1.4 on 2026-05-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panservice', '0032_psamaster_balance_psamaster_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponpurchase',
            name='amount_deducted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='couponpurchase',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='couponpurchase',
            name='psa_status',
            field=models.CharField(choices=[('issued', 'Issued'), ('started', 'Started'), ('partially_completed', 'Partially Completed'), ('fully_completed', 'Fully Completed')], default='issued', max_length=30),
        ),
        migrations.AddField(
            model_name='couponpurchase',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='couponpurchase',
            name='submission_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
