# Generated by Django 5.1.4 on 2026-06-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panservice', '0033_couponpurchase_amount_deducted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponpurchase',
            name='rerequest_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='couponpurchase',
            name='rerequest_status',
            field=models.CharField(choices=[('none', 'None'), ('requested', 'Requested'), ('approved', 'Approved')], default='none', max_length=20),
        ),
    ]
