# Generated by Django 5.0.3 on 2025-03-09 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_centreuseraccount_another_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centreuseraccount',
            name='another_name',
        ),
        migrations.RemoveField(
            model_name='centreuseraccount',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='centreuseraccount',
            name='old_user',
        ),
    ]
