# Generated by Django 5.1.4 on 2025-05-13 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_table_accountsmaster_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='voucherconfiguration',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='voucherconfiguration',
            name='user',
        ),
    ]
