# Generated by Django 5.1.4 on 2025-05-13 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_voucherconfiguration_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherconfiguration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='voucherconfiguration',
            unique_together={('user', 'category', 'series')},
        ),
    ]
