# Generated by Django 5.1.4 on 2025-06-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_voucherconfiguration_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centreuseraccount',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
