# Generated by Django 5.1.4 on 2025-07-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_centreuseraccount_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centreuseraccount',
            name='ward_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
