# Generated by Django 5.1.4 on 2025-07-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_centreuseraccount_ward_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centreuseraccount',
            name='ward_number',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
