# Generated by Django 5.2.17 on 2026-09-16 12:19

import django.db.models.deletion
import web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='stateservice',
            name='service_details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='StateServiceDetailImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=web.models.service_detail_image_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_images', to='web.stateservice')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
    ]
