# Generated by Django 5.2.17 on 2026-09-17 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_stateservice_service_details_stateservicedetailimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadform',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_forms', to='web.stateservice'),
        ),
        migrations.AddField(
            model_name='downloadform',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_forms', to='web.addstate'),
        ),
    ]
