# Generated by Django 5.2.17 on 2026-09-17 07:11

from django.db import migrations, models


def add_thumbnail_column(apps, schema_editor):
    online_class = apps.get_model("web", "OnlineClass")
    field = models.ImageField(
        name="thumbnail", upload_to="media/", blank=True, null=True
    )
    field.set_attributes_from_name("thumbnail")
    field.model = online_class
    columns = {
        column.name
        for column in schema_editor.connection.introspection.get_table_description(
            schema_editor.connection.cursor(), online_class._meta.db_table
        )
    }
    if field.column not in columns:
        schema_editor.add_field(online_class, field)


def remove_thumbnail_column(apps, schema_editor):
    online_class = apps.get_model("web", "OnlineClass")
    field = models.ImageField(
        name="thumbnail", upload_to="media/", blank=True, null=True
    )
    field.set_attributes_from_name("thumbnail")
    field.model = online_class
    columns = {
        column.name
        for column in schema_editor.connection.introspection.get_table_description(
            schema_editor.connection.cursor(), online_class._meta.db_table
        )
    }
    if field.column in columns:
        schema_editor.remove_field(online_class, field)


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_downloadform_service_downloadform_state'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_thumbnail_column,
                    remove_thumbnail_column,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="onlineclass",
                    name="thumbnail",
                    field=models.ImageField(
                        blank=True, null=True, upload_to="media/"
                    ),
                ),
            ],
        ),
    ]
