# Generated by Django 5.2.17 on 2026-09-17 08:02

import web.models
from django.db import migrations, models
from django.db.models import Q
from django.utils.text import slugify


def populate_online_class_slugs(apps, schema_editor):
    online_class_model = apps.get_model("web", "OnlineClass")
    for online_class in online_class_model.objects.filter(
        Q(slug__isnull=True) | Q(slug="")
    ).order_by("pk"):
        base_slug = slugify(online_class.title) or "online-class"
        candidate = base_slug
        suffix = 2
        while online_class_model.objects.filter(slug=candidate).exclude(
            pk=online_class.pk
        ).exists():
            candidate = f"{base_slug}-{suffix}"
            suffix += 1
        online_class_model.objects.filter(pk=online_class.pk).update(slug=candidate)


def clear_online_class_slugs(apps, schema_editor):
    apps.get_model("web", "OnlineClass").objects.update(slug=None)


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_onlineclass_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineclass',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='onlineclass',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=web.models.online_class_video_upload_to),
        ),
        migrations.RunPython(
            populate_online_class_slugs,
            clear_online_class_slugs,
        ),
        migrations.AlterField(
            model_name='onlineclass',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
