# Generated by Django 5.2.17 on 2026-09-21 07:16

import django.db.models.deletion
import web.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_onlineclass_slug_onlineclass_video_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchiseEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('franchise_centre_name', models.CharField(max_length=255)),
                ('franchise_user_name', models.CharField(max_length=255)),
                ('franchise_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=10000)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=web.models.franchise_enquiry_attachment_path)),
                ('status', models.CharField(choices=[('open', 'Open'), ('replied', 'Replied'), ('closed', 'Closed')], db_index=True, default='open', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_reply', models.TextField(blank=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='web.centreuseraccount')),
                ('replied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replied_franchise_enquiries', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='franchise_enquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Franchise enquiry',
                'verbose_name_plural': 'Franchise enquiries',
                'ordering': ('-created_at', '-pk'),
            },
        ),
    ]
