# Generated by Django 5.2.17 on 2026-09-21 07:33

import web.models
import web.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_franchiseenquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchiseenquiry',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=web.storages.FranchiseEnquiryStorage(), upload_to=web.models.franchise_enquiry_attachment_path),
        ),
    ]
