# Generated by Django 5.2.17 on 2026-09-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_alter_franchiseenquiry_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchiseenquiry',
            name='original_notification_message_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
