# Generated by Django 5.2.17 on 2026-09-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0016_franchiseenquiry_original_notification_message_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
