# Generated by Django 5.2.17 on 2026-09-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_user_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='addstate',
            name='whatsapp_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='addstate',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
