# Generated by Django 5.2.17 on 2026-09-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0020_repair_legacy_transaction_user_columns"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stateservice",
            name="service_logo",
            field=models.ImageField(
                blank=True,
                upload_to="media/servicelogo",
            ),
        ),
    ]
