# Generated by Django 5.2.17 on 2026-09-24 10:05

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_alter_stateservice_service_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentreReactivationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inactivity_days', models.PositiveIntegerField(default=90, help_text='Number of days without a successful login before inactivity disablement.', validators=[django.core.validators.MinValueValidator(1)])),
                ('default_amount', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_enabled', models.BooleanField(default=True)),
                ('admin_message', models.TextField(default='Your centre has been temporarily disabled because there has been no login activity for more than 3 months. Please contact Head Office or complete the reactivation payment to continue.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Centre Reactivation Setting',
                'verbose_name_plural': 'Centre Reactivation Settings',
            },
        ),
        migrations.AddField(
            model_name='centreuseraccount',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='centreuseraccount',
            name='inactive_due_to_inactivity',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='centreuseraccount',
            name='inactivity_disabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centreuseraccount',
            name='inactivity_reason',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='centreuseraccount',
            name='last_successful_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centreuseraccount',
            name='manual_disabled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='centreuseraccount',
            name='reactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centreuseraccount',
            name='reactivation_fee_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.CreateModel(
            name='CentreReactivationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('inactivity_disabled', 'Inactivity disabled'), ('payment_attempt', 'Payment attempt'), ('payment_pending', 'Payment pending'), ('payment_failed', 'Payment failed'), ('payment_cancelled', 'Payment cancelled'), ('payment_success', 'Payment success'), ('reactivated', 'Reactivated'), ('manual_review', 'Manual review')], max_length=32)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centre_reactivation_audit_events', to=settings.AUTH_USER_MODEL)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactivation_audit_logs', to='web.centreuseraccount')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='CentreReactivationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('manual_review', 'Manual review')], db_index=True, default='created', max_length=20)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('razorpay_signature', models.CharField(blank=True, default='', max_length=256)),
                ('failure_code', models.CharField(blank=True, default='', max_length=100)),
                ('failure_description', models.TextField(blank=True, default='')),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactivation_payments', to='web.centreuseraccount')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
    ]
