# Generated by Django 5.2.17 on 2026-09-24 11:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_centrereactivationsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centreuseraccount',
            name='manual_disable_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='centreuseraccount',
            name='manual_disabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centreuseraccount',
            name='manual_disabled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manually_disabled_centres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='centreuseraccount',
            name='manual_reactivation_fee_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='centreuseraccount',
            name='manual_reactivation_payment_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='centrereactivationauditlog',
            name='event',
            field=models.CharField(choices=[('inactivity_disabled', 'Inactivity disabled'), ('manual_disabled', 'Manual disable'), ('manual_enabled', 'Manual enable'), ('payment_attempt', 'Payment attempt'), ('payment_pending', 'Payment pending'), ('payment_failed', 'Payment failed'), ('payment_cancelled', 'Payment cancelled'), ('payment_success', 'Payment success'), ('reactivated', 'Reactivated'), ('manual_review', 'Manual review')], max_length=32),
        ),
    ]
