from django.urls import path
from panservice import views

urlpatterns = [
    path('', views.home_view, name = 'home'),
    path('about/', views.about_view, name = 'about'),
    path('privacy_policy/', views.privacy_policy, name = 'privacy_policy'),
    path('terms_condition/', views.terms_condition_view, name = 'terms_condition'),
    path('register/', views.register_view, name = 'register'),
    path('send-otp/', views.send_email_otp, name='send_otp'),
    path('verify-otp/', views.verify_email_otp, name='verify_otp'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('create-user/', views.create_user, name = 'create_user'),
    path("all-users/", views.all_users, name="all_users"),
    path("approve-user/<int:user_id>/", views.approve_user, name="approve_user"),
    path("reject-user/<int:user_id>/", views.reject_user, name="reject_user"),
    path('delete-user/<int:user_id>/', views.delete_user, name='delete_user'),
    path('admin-change-password/<int:user_id>/',views.admin_change_user_password,name='admin_change_user_password'),
    path("get-districts/", views.get_districts, name="get_districts"),
    path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('state-dashboard/', views.state_dashboard, name='state_dashboard'),
    path('district-dashboard/', views.district_dashboard, name='district_dashboard'),
    path('retailer-dashboard/', views.retailer_dashboard, name='retailer_dashboard'),
    path('district-list/', views.district_list, name='district_list'),
    path('role-redirect/', views.role_redirect, name='role_redirect'),
    path('state/create-user/', views.state_create_user, name='state_create_user'),
    path('state/profile/', views.state_profile, name='state_profile'),
    path('state/created-users/', views.state_created_users, name = 'state_created_users'),

    path('state/<int:user_id>/districts/', views.state_districts_list, name='state_districts_list'),
    path('state/<int:user_id>/retailers/', views.state_retailers_list, name='state_retailers_list'),

    path('state-distributor/<int:user_id>/', views.state_distributor_profile, name='state_distributor_profile'),

    # KEEP THIS LAST
    path('state/<str:state_name>/', views.state_details, name='state_details'),
    path('districts/admin/', views.admin_created_districts, name='admin_created_districts'),   
    path('retailers/', views.list_retailers, name='list_retailers'),
    path('retailer/profile/<int:user_id>/', views.retailer_profile, name='retailer_profile'),
    path('state/district/<int:district_id>/retailers/', views.state_district_retailers,name='state_district_retailers'),
    path('admin-created-retailers/',views.admin_created_retailers, name='admin_created_retailers'),
    path('district/create-user/', views.district_create_user, name = 'district_create_user'),
    path('district/created-users/', views.district_created_users, name = 'district_created_users'),
    path('district/profile/',views. district_profile, name='district_profile'),
    path('edit-contact/', views.edit_contact, name='edit_contact'),
    path('wallet/add/',views.add_money, name='add_money'),
    path('wallet/add/proceed/',views.add_money_proceed, name='add_money_proceed'),
    path('wallet/status/<int:req_id>/',views. wallet_status, name='wallet_status'),
    path('wallet/requests/',views. wallet_requests_admin, name='wallet_requests_admin'),
    path('wallet/approve/<int:req_id>/',views. approve_wallet, name='approve_wallet'),
    path('wallet/reject/<int:req_id>/', views.reject_wallet, name='reject_wallet'),
    path('wallet/my-requests/', views.my_wallet_requests, name='my_wallet_requests'),
    path('wallet/approved/',views. wallet_approved_history, name='wallet_approved_history'),
    path('wallet/transactions/', views.my_transactions, name='my_transactions'),
    path('wallet/all-transactions/',views. all_transactions, name='all_transactions'),
    path('wallet/admin-withdraw/', views.admin_withdraw, name='admin_withdraw'),
    path('wallet/admin-add-money/', views.admin_add_money, name='admin_add_money'),
    path('buy-coupons/', views.buy_coupons, name='buy_coupons'),
    path('coupon-requests/', views.coupon_requests_admin, name='coupon_requests_admin'),
    path('my-coupon-requests/',views. my_coupon_requests, name='my_coupon_requests'),
    path('psa-lifecycle/<int:req_id>/', views.update_psa_lifecycle, name='update_psa_lifecycle'),
    path('approve-coupon/<int:req_id>/',views. approve_coupon_psa, name='approve_coupon_psa'),
    path('view-psa/<int:req_id>/', views.view_psa_details, name='view_psa_details'),
    path('psa-assigned-list/',views. psa_assigned_list_admin, name='psa_assigned_list_admin'),
    path('psa-assigned-list/update-password/', views.update_psa_assigned_password, name='update_psa_assigned_password'),
    path('request_psa_again/<int:req_id>/', views.request_psa_again, name = 'request_psa_again'),
    path('psa-rerequests/', views.psa_rerequests_admin, name='psa_rerequests_admin'),
    path('psa-rerequests/<int:req_id>/approve/', views.approve_psa_rerequest, name='approve_psa_rerequest'),
    path('psa-rerequests/update-password/', views.update_psa_rerequest_password, name='update_psa_rerequest_password'),
    # path('mark-done/<int:req_id>/',views. mark_done_psa, name='mark_done_psa'),
    path('my-commissions/', views.my_commissions, name='my_commissions'),
    path('admin-commission-dashboard/', views.admin_commission_dashboard, name='admin_commission_dashboard'),
    path('my-earning/', views.distributor_commission_dashboard, name='distributor_commission_dashboard'),
    path('withdraw-requests/', views.admin_withdraw_requests, name='admin_withdraw_requests'),
    path('withdraw-approve/<int:req_id>/', views.approve_commission_withdraw, name='approve_commission_withdraw'),
    path('withdraw-reject/<int:req_id>/', views.reject_commission_withdraw, name='reject_commission_withdraw'),
    path('withdraw-commission/', views.request_commission_withdraw, name='request_commission_withdraw'),
    path('commission/wallet/', views.my_commission_wallet, name='my_commission_wallet'),
    path('commission/history/',views. commission_history, name='commission_history'),
    path('change-password/', views.ChangePasswordView.as_view(), name='change_password'),
    path('password-change-done/',views. password_change_done, name='password_change_done'),
    path('commission-withdraw/', views.admin_commission_withdraw, name='admin_commission_withdraw'),
    path('admin/all-commissions/', views. admin_all_commissions, name='admin_all_commissions'),
    
    # PSA Master
    path('psa-master/', views.psa_master_list, name='psa_master_list'),
    path('psa-master/all-history/', views.all_psa_history, name='all_psa_history'),
    path('psa-master/add/', views.psa_master_add, name='psa_master_add'),
    path('psa-master/edit/<int:pk>/', views.psa_master_edit, name='psa_master_edit'),
    path('psa-master/delete/<int:pk>/', views.psa_master_delete, name='psa_master_delete'),
]
