"""
Django settings for ssc project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from decouple import config
import os

from dotenv import load_dotenv
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-o8h523dr=hub@2=g#9kpdijqx3m%s*j5wbsik)j6^#i8ctatt^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['localhost', '127.0.0.1']
ALLOWED_HOSTS = ['*', 'sscegov.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'web',
    'registration',
    'crispy_forms',
    'crispy_bootstrap5',
    "captcha",
    "exam", 
    # "axes",
    # 'csp',
    # 'compressor',

]

MIDDLEWARE = [
    # 'csp.middleware.CSPMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'axes.middleware.AxesMiddleware',
    # 'web.middleware.HostHeaderValidationMiddleware',  # Ensure this is correct
    # 'web.middleware.XSSProtectionMiddleware',
    # 'web.middleware.ContentSecurityPolicyMiddleware',
    # 'web.middleware.NoCacheMiddleware',
    # 'web.middleware.SingleSessionMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    #  'web.middleware.ContentSecurityPolicyMiddleware',
    # 'axes.middleware.AxesMiddleware',
]

# MIDDLEWARE += [
#     'axes.middleware.AxesMiddleware',
# ]
# Authentication backends
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    # "axes.backends.AxesStandaloneBackend",  # Optional, for security features
]

ROOT_URLCONF = 'ssc.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'web.context_processors.franchise_service_navigation',
            ],
        },
    },
]


# WSGI_APPLICATION = 'ssc.wsgi.application'
# WSGI_APPLICATION = 'ssc.wsgi.application'



# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'sscegov',
#         'USER': 'root',
#         'PASSWORD': 'pentagon',
#         'HOST': 'localhost',
#         'PORT': '3306',
#         'OPTIONS': {
#             'charset': 'utf8',  
#         },
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]

ANYMAIL = {
    "BREVO": {
        "API_KEY": os.getenv("BREVO_API_KEY", "your-brevo-api-key"),
    }
}
EMAIL_BACKEND = "anymail.backends.brevo.EmailBackend"
DEFAULT_FROM_EMAIL = "samatwaservicecenter.gov.in@gmail.com"




# # Rate limiting (Axes settings)
# AXES_FAILURE_LIMIT = 5
# AXES_COOLOFF_TIME = 1  # in hours
# AXES_LOCK_OUT_AT_FAILURE = True

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Whitenoise settings
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

STATIC_URL = '/test/static/'
MEDIA_URL = '/test/media/'
FORCE_SCRIPT_NAME = '/test'

MEDIA_ROOT = BASE_DIR / 'media'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATICFILES_DIRS = [BASE_DIR / 'static']  # This is where your static files are located
STATIC_ROOT = BASE_DIR / 'assets'  # This is where collectstatic will collect files
BASE_DIR = Path(__file__).resolve().parent.parent
if DEBUG:
    import mimetypes    
    mimetypes.add_type("text/css", ".css", True)
    MIDDLEWARE += [
        'django.middleware.security.SecurityMiddleware',
        'whitenoise.middleware.WhiteNoiseMiddleware',
    ]

    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

ACCOUNT_ACTIVATION_DAYS = 7
REGISTRATION_AUTO_LOGIN = True
SEND_ACTIVATION_EMAIL = True
REGISTRATION_EMAIL_SUBJECT_PREFIX = ''

REGISTRATION_OPEN = True
LOGIN_URL = '/custom_login'
LOGOUT_URL = '/accounts/logout/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'
# For email   
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp-relay.brevo.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = '79f983002@smtp-brevo.com'
# EMAIL_HOST_PASSWORD = '9YLzAk1PNcDMfQqI'
EMAIL_BACKEND = config("EMAIL_BACKEND")
EMAIL_HOST = config("EMAIL_HOST")
EMAIL_PORT = config("EMAIL_PORT")
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'web.User'

load_dotenv()


TIME_ZONE = 'Asia/Kolkata'
USE_TZ = True


# Razorpay API
RAZORPAY_KEY_ID = os.getenv("RAZORPAY_KEY_ID", "rzp_live_nSEm6ZJdnKS1Ov")
RAZORPAY_KEY_SECRET = os.getenv("RAZORPAY_KEY_SECRET", "54bep8rW085LCIk6rySSDcr2")


# PSPDFKit API key
PSPDFKIT_API_KEY = os.getenv("PSPDFKIT_API_KEY", "")

# reCAPTCHA keys
RECAPTCHA_SITE_KEY = os.getenv("RECAPTCHA_SITE_KEY", "6LfhACgqAAAAAH6BOnzNkIfbY-yRgk_XCNKWTH8i")
RECAPTCHA_SECRET_KEY = os.getenv("RECAPTCHA_SECRET_KEY", "6LfhACgqAAAAAFqwP-iG32CZyREH66J6u43F-I8D")


# Secure Proxy Header
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


CSRF_FAILURE_VIEW = 'web.views.custom_csrf_failure'

CSRF_TRUSTED_ORIGINS = ['https://sscegov.com', 'https://checkout.razorpay.com/v1/checkout.js']




LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
}








# CSP_DEFAULT_SRC = ("'self'",)

# # Allowing external stylesheets (Boxicons)


# CSP_STYLE_SRC = (
#     "'self'",
#     "'unsafe-inline'",
#     "https://fonts.googleapis.com",
#     "https://cdnjs.cloudflare.com",
# )

# # Allow external scripts (Razorpay, Google Tag Manager)
# CSP_SCRIPT_SRC = (
#     # "'self'", 
#     # "'nonce-WfKHleDV7mWuv/C3kiAr9w=='",  # Nonce for inline scripts
#     # "https://checkout.razorpay.com",  # Razorpay
#     # "https://www.googletagmanager.com",  
#     # "https://cdn.amcharts.com",  
#     "https://cdn.jsdelivr.net",
# )


# # Allow images from self and data URLs
# CSP_IMG_SRC = ("'self'", "data:")

# Allow Google Fonts


STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'




# CSP_FONT_SRC = ("'self'", "https://fonts.gstatic.com")  # Allow Google Fonts
# CSP_CONNECT_SRC = ("'self'", "https://api.razorpay.com", "https://rzp.io")





# CSP_FONT_SRC = ("'self'", "https://fonts.gstatic.com")  # Allow Google Fonts
# CSP_CONNECT_SRC = ("'self'", "https://api.razorpay.com", "https://rzp.io")





# CSP_SCRIPT_SRC = [
#     "'self'",
#     "'nonce-wLYOFp5kGDsknXG7ZMetvA=='",
#     "cdn.amcharts.com",
#     "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js",
# ]

# CSP_STYLE_SRC = [
#     "'self'",
#     "'unsafe-inline'",
#     "https://fonts.googleapis.com",
#     "https://afsal.com/boxicons@2.1.4/css/boxicons.min.css",
#     "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css",
# ]

# CSP_FONT_SRC = [
#     "'self'",
#     "https://fonts.googleapis.com",
#     "https://fonts.gstatic.com",
# ]

# CSP_IMG_SRC = [
#     "'self'",
#     "data:",
#     "https://cdn.gtranslate.net/",
#     "https://i.ytimg.com/",
# ]

# CSP_FRAME_SRC = [
#     "'self'",
#     "https://open.spotify.com",
#     "https://api.razorpay.com",
# ]

# CSP_CONNECT_SRC = [
#     "'self'",
#     "https://sscegov.com/",
# ]

# CSP_REPORT_URI = "/csp-report-endpoint"
# CSP_IMG_SRC = ("'self'", "data:", "https://cdn.gtranslate.net", "https://i.ytimg.com/")
# CSP_STYLE_SRC_ELEM = ("'self'", "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css")
# CSP_STYLE_SRC_ELEM = ("'self'", "https://cdn.jsdelivr.net")
# CSP_STYLE_SRC_ELEM = ("'self'", "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css")
# CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css")
# CSP_SCRIPT_SRC = ("'self'", "cdn.amcharts.com")
# CSP_FRAME_SRC = ("'self'", "https://open.spotify.com", "https://api.razorpay.com")
# CSP_CONNECT_SRC = ("'self'", "https://sscegov.com/", "https://api.razorpay.com")
# CSP_SCRIPT_SRC = ("'self'", "cdn.amcharts.com", "https://checkout.razorpay.com")
# CSP_FRAME_SRC = ("'self'", "https://open.spotify.com", "https://api.razorpay.com")
# CSP_FRAME_SRC = ("'self'", "https://open.spotify.com", "https://api.razorpay.com")
# CSP_FRAME_ANCESTORS = ("'self'", "https://open.spotify.com", "https://api.razorpay.com")
# CSP_CONNECT_SRC = ("'self'", "https://sscegov.com/", "https://api.razorpay.com")
# CSP_FRAME_SRC = ("'self'", "https://open.spotify.com", "https://api.razorpay.com")
# CSP_FRAME_ANCESTORS = ("'self'", "https://open.spotify.com", "https://api.razorpay.com")
# CSP_SCRIPT_SRC = ("'self'", "cdn.amcharts.com", "https://checkout.razorpay.com")
# CSP_WORKER_SRC = ("'self'", "https://api.razorpay.com")



# CSP_DEFAULT_SRC = ("'self'",)
# CSP_SCRIPT_SRC = ("'self'", "'nonce-G6IKR6kYWFtYtG2RGHwnow=='", "cdn.amcharts.com")
# CSP_IMG_SRC = ("'self'", "data:", "https://cdn.gtranslate.net/", "https://i.ytimg.com/")
# CSP_FONT_SRC = ("'self'", "https://fonts.googleapis.com/", "https://fonts.gstatic.com/")
# CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", "https://fonts.googleapis.com/")
# CSP_STYLE_SRC_ELEM = ("'self'", "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css")
# CSP_FRAME_ANCESTORS = ("'self'", "https://open.spotify.com")
# CSP_FRAME_SRC = ("'self'", "https://open.spotify.com")
# CSP_CONNECT_SRC = ("'self'", "https://sscegov.com/")
# CSP_WORKER_SRC = ("'self'",)
# CSP_REPORT_URI = "/csp-report-endpoint"
# CSP_DEFAULT_SRC = ("'self'",)
# CSP_SCRIPT_SRC = ("'self'", "cdn.amcharts.com", "https://checkout.razorpay.com")
# CSP_IMG_SRC = ("'self'", "data:", "https://cdn.gtranslate.net/", "https://i.ytimg.com/")
# CSP_FONT_SRC = ("'self'", "https://fonts.googleapis.com/", "https://fonts.gstatic.com/")
# CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css")
# CSP_STYLE_SRC_ELEM = ("'self'", "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css")
# CSP_FRAME_SRC = ("'self'", "https://open.spotify.com", "https://api.razorpay.com")
# CSP_CONNECT_SRC = ("'self'", "https://sscegov.com/", "https://api.razorpay.com")
# CSP_WORKER_SRC = ("'self'",)
# CSP_REPORT_URI = "/csp-report-endpoint"
# CSP_DEFAULT_SRC = ("'self'",)
# CSP_SCRIPT_SRC = ("'self'", "cdn.amcharts.com", "https://checkout.razorpay.com")
# CSP_IMG_SRC = ("'self'", "data:", "https://cdn.gtranslate.net/", "https://i.ytimg.com/")
# CSP_FONT_SRC = ("'self'", "https://fonts.googleapis.com/", "https://fonts.gstatic.com/")
# CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css")
# CSP_STYLE_SRC_ELEM = ("'self'", "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css")
# CSP_FRAME_SRC = ("'self'", "https://open.spotify.com", "https://api.razorpay.com")
# CSP_CONNECT_SRC = ("'self'", "https://sscegov.com/", "https://api.razorpay.com")
# CSP_WORKER_SRC = ("'self'",)
# CSP_REPORT_URI = "/csp-report-endpoint"
# CSP_DEFAULT_SRC = ("'self'",)
# CSP_SCRIPT_SRC = ("'self'", "cdn.amcharts.com", "https://checkout.razorpay.com")
# CSP_IMG_SRC = ("'self'", "data:", "https://cdn.gtranslate.net/", "https://i.ytimg.com/")
# CSP_FONT_SRC = ("'self'", "https://fonts.googleapis.com/", "https://fonts.gstatic.com/")
# CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css")
# CSP_STYLE_SRC_ELEM = ("'self'", "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css")
# CSP_FRAME_SRC = ("'self'", "https://open.spotify.com", "https://api.razorpay.com")
# CSP_FRAME_ANCESTORS = ("'self'", "https://open.spotify.com", "https://api.razorpay.com")
# CSP_CONNECT_SRC = ("'self'", "https://sscegov.com/", "https://api.razorpay.com")
# CSP_WORKER_SRC = ("'self'",)
# CSP_REPORT_URI = "/csp-report-endpoint"



# CSP_DEFAULT_SRC = ["'self'"]
# CSP_SCRIPT_SRC = ["'self'", "'nonce-5Z+NHTJzJKvVZGDU+4YZug=='", "cdn.amcharts.com"]
# CSP_IMG_SRC = ["'self'", "data:", "https://cdn.gtranslate.net/", "https://i.ytimg.com/"]
# CSP_FONT_SRC = ["'self'", "https://fonts.googleapis.com/", "https://fonts.gstatic.com/"]
# CSP_STYLE_SRC = ["'self'", "'unsafe-inline'", "https://fonts.googleapis.com/"]
# CSP_FRAME_SRC = ["'self'", "https://open.spotify.com", "https://api.razorpay.com"]
# CSP_CONNECT_SRC = ["'self'", "https://sscegov.com/"]
# CSP_WORKER_SRC = ["'self'"]

# # Report endpoint
# CSP_REPORT_URI = "/csp-report-endpoint"


# CSP_SCRIPT_SRC = [
#     "'self'",
#     "'nonce-1ByWJYH4hwnWKBbWz9TOJg=='",
#     "cdn.amcharts.com",
#     "cdn.jsdelivr.net"
# ]

# CSP_SCRIPT_SRC = [
#     "'self'",
#     "'nonce-1ByWJYH4hwnWKBbWz9TOJg=='",
#     "cdn.amcharts.com",
#     "unpkg.com"
# ]


FILE_CHARSET = 'utf-8'
DEFAULT_CHARSET = 'utf-8'


OPTIONS = {
    'charset': 'utf8mb4',
}
