# Generated by Django 5.1.4 on 2025-02-17 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationState',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField()),
                ('reply', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MainExamProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Not Attempted', 'Not Attempted'), ('Passed', 'Passed'), ('Failed Attempt 1', 'Failed Attempt 1'), ('Failed Attempt 2', 'Failed Attempt 2')], default='Not Attempted', max_length=20)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('attempt_number', models.IntegerField(default=1)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_exam_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MainExamOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exam.mainexamquestion')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=510)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('exam_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam.examcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(blank=True, max_length=510, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exam.question')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationDistrict',
            fields=[
                ('district_id', models.AutoField(primary_key=True, serialize=False)),
                ('district_name', models.CharField(max_length=100)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.registrationstate')),
            ],
            options={
                'unique_together': {('state', 'district_name')},
            },
        ),
        migrations.CreateModel(
            name='TemporaryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('another_name', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(db_column='district_id', max_length=100)),
                ('panchayat', models.CharField(max_length=255)),
                ('ward_number', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('transgender', 'Transgender')], max_length=20)),
                ('aadhaar_number', models.CharField(max_length=12, unique=True)),
                ('cheque_passbook', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=455)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('payment', models.BooleanField(default=False)),
                ('pan', models.ImageField(blank=True, null=True, upload_to='pan/')),
                ('registration_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('certificate_paid', models.BooleanField(default=False)),
                ('certificate_downloaded', models.BooleanField(default=False)),
                ('details_filled', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TecExamProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Locked', 'Locked'), ('Failed', 'Failed'), ('Passed', 'Passed')], default='Open', max_length=10)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('exam_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_progress', to='exam.examcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_progress', to='exam.temporaryuser')),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('another_name', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(db_column='district_id', max_length=100)),
                ('panchayat', models.CharField(max_length=255)),
                ('ward_number', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('transgender', 'Transgender')], max_length=20)),
                ('aadhaar_number', models.CharField(max_length=12, unique=True)),
                ('cheque_passbook', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=455)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('pan', models.ImageField(blank=True, null=True, upload_to='pan/')),
                ('certificate_paid', models.BooleanField(default=False)),
                ('certificate_downloaded', models.BooleanField(default=False)),
                ('details_filled', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=2.0)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failure', 'Failure'), ('Pending', 'Pending')], default='Pending', max_length=254)),
                ('provider_order_id', models.CharField(max_length=40)),
                ('payment_id', models.CharField(max_length=36)),
                ('signature_id', models.CharField(max_length=128)),
                ('is_certificate_payment', models.BooleanField(default=False)),
                ('user_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.userregistration')),
            ],
        ),
        migrations.CreateModel(
            name='VideoRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_records', to='exam.temporaryuser')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationPanchayat',
            fields=[
                ('panchayat_id', models.AutoField(primary_key=True, serialize=False)),
                ('panchayat_name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.registrationdistrict')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.registrationstate')),
            ],
            options={
                'unique_together': {('state', 'district', 'panchayat_name')},
            },
        ),
    ]
