# Generated by Django 5.1.4 on 2025-02-17 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='videorecord',
            table='video_record',
        ),
    ]
