# Generated by Django 5.1.4 on 2025-02-17 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_alter_videorecord_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='videorecord',
            table=None,
        ),
    ]
