# Generated by Django 5.1.4 on 2025-02-17 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_alter_videorecord_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videorecord',
            name='user_registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_records', to='exam.temporaryuser'),
        ),
    ]
