# Generated by Django 5.1.4 on 2025-02-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_alter_videorecord_user_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationpanchayat',
            name='local_body',
            field=models.CharField(choices=[('Panchayath', 'Panchayath'), ('Muncipality', 'Muncipality'), ('Corporation', 'Corporation')], default='Panchayath', max_length=30),
        ),
        migrations.AddField(
            model_name='temporaryuser',
            name='local_body',
            field=models.CharField(choices=[('Panchayath', 'Panchayath'), ('Muncipality', 'Muncipality'), ('Corporation', 'Corporation')], default='Panchayath', max_length=30),
        ),
    ]
