# Generated by Django 5.1.4 on 2025-02-18 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_registrationpanchayat_local_body_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoRecord',
        ),
    ]
