# Generated by Django 5.1.4 on 2025-02-18 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_delete_videorecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_records', to='exam.temporaryuser')),
            ],
        ),
    ]
