# Generated by Django 5.1.4 on 2025-02-18 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_videorecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoRecord',
        ),
    ]
