# Generated by Django 5.1.4 on 2025-02-20 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_delete_videorecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationpanchayat',
            old_name='panchayat_name',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='registrationpanchayat',
            unique_together={('state', 'district', 'name')},
        ),
    ]
