# Generated by Django 5.1.4 on 2025-02-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_rename_panchayat_name_registrationpanchayat_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryuser',
            name='lattitude',
            field=models.FloatField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='temporaryuser',
            name='longitude',
            field=models.FloatField(blank=True, max_length=500, null=True),
        ),
    ]
