# Generated by Django 5.1.4 on 2025-02-24 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_temporaryuser_lattitude_temporaryuser_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporaryuser',
            name='details_filled',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='details_filled',
        ),
    ]
