# Generated by Django 5.1.4 on 2025-02-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryuser',
            name='main_exam_passed',
            field=models.BooleanField(default=False),
        ),
    ]
