# Generated by Django 5.1.4 on 2025-03-01 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_temporaryuser_main_exam_passed'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='document_validation/')),
                ('aadhaar', models.ImageField(upload_to='document_validation/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.temporaryuser')),
            ],
        ),
    ]
