# Generated by Django 5.1.4 on 2025-03-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_documentvalidation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainexamregistration',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
