# Generated by Django 5.1.4 on 2025-03-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_alter_mainexamregistration_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryuser',
            name='aadhaar_back',
            field=models.ImageField(blank=True, null=True, upload_to='aadhaar/'),
        ),
        migrations.AddField(
            model_name='temporaryuser',
            name='aadhaar_front',
            field=models.ImageField(blank=True, null=True, upload_to='aadhaar/'),
        ),
        migrations.AddField(
            model_name='temporaryuser',
            name='centre_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='temporaryuser',
            name='centre_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='temporaryuser',
            name='centre_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='temporaryuser',
            name='centre_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='temporaryuser',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='temporaryuser',
            name='pincode',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='temporaryuser',
            name='sign',
            field=models.ImageField(blank=True, null=True, upload_to='Sign/'),
        ),
        migrations.AddField(
            model_name='temporaryuser',
            name='sslc',
            field=models.ImageField(blank=True, null=True, upload_to='SSLC/'),
        ),
        migrations.AddField(
            model_name='temporaryuser',
            name='taluk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
