# Generated by Django 5.1.4 on 2025-03-04 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0018_temporaryuser_aadhaar_back_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporaryuser',
            name='aadhaar_back',
        ),
        migrations.RemoveField(
            model_name='temporaryuser',
            name='aadhaar_front',
        ),
        migrations.RemoveField(
            model_name='temporaryuser',
            name='centre_address',
        ),
        migrations.RemoveField(
            model_name='temporaryuser',
            name='centre_email',
        ),
        migrations.RemoveField(
            model_name='temporaryuser',
            name='centre_name',
        ),
        migrations.RemoveField(
            model_name='temporaryuser',
            name='centre_phone',
        ),
        migrations.RemoveField(
            model_name='temporaryuser',
            name='pan',
        ),
        migrations.RemoveField(
            model_name='temporaryuser',
            name='pan_number',
        ),
        migrations.RemoveField(
            model_name='temporaryuser',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='temporaryuser',
            name='sign',
        ),
        migrations.RemoveField(
            model_name='temporaryuser',
            name='sslc',
        ),
        migrations.RemoveField(
            model_name='temporaryuser',
            name='taluk',
        ),
    ]
